#!/usr/bin/env bash
# AGENT-007-CHOOSE-STORAGE.sh — Interactive drive/storage picker for Agent-007.
# Lets you choose which drive or folder to use for each data category
# (LLM models, image models, outputs, cache, logs, downloads, etc.)
# and writes .agent-007-storage-config.env so all Agent-007 scripts respect it.
#
# Usage:
#   bash AGENT-007-CHOOSE-STORAGE.sh
#   bash AGENT-007-CHOOSE-STORAGE.sh --auto   # auto-detect, no prompts
#   bash AGENT-007-CHOOSE-STORAGE.sh --list   # list drives and exit

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAMP="$(date +%Y%m%d-%H%M%S)"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'
RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'

say()  { printf '%b\n' "${CYAN}[INFO]${NC} $*"; }
ok()   { printf '%b\n' "${GREEN}[OK]${NC} $*"; }
warn() { printf '%b\n' "${YELLOW}[WARN]${NC} $*"; }
die()  { printf '%b\n' "${RED}[ERROR]${NC} $*" >&2; exit 1; }

# ── Detect mounted volumes ───────────────────────────────────────────
declare -a DRIVE_PATHS=()
declare -a DRIVE_LABELS=()
declare -a DRIVE_FREE_GB=()
declare -a DRIVE_TOTAL_GB=()

detect_drives() {
  local line mount_path free_kb total_kb free_gb total_gb label
  # macOS and Linux standard mount points
  while IFS= read -r line; do
    mount_path="$(echo "$line" | awk '{print $NF}')"
    case "$mount_path" in
      /Volumes/*|/media/*|/run/media/*|/mnt/*) ;;
      /) ;; # include root
      *) continue ;;
    esac
    total_kb="$(echo "$line" | awk '{print $2}')"
    free_kb="$(echo "$line" | awk '{print $4}')"
    [ -z "$free_kb" ] && continue
    [ "$total_kb" -lt 1048576 ] 2>/dev/null && continue  # skip < 1GB
    total_gb=$((total_kb / 1024 / 1024))
    free_gb=$((free_kb / 1024 / 1024))
    label="$(basename "$mount_path")"
    [ "$mount_path" = "/" ] && label="(internal disk)"
    DRIVE_PATHS+=("$mount_path")
    DRIVE_LABELS+=("$label")
    DRIVE_FREE_GB+=("$free_gb")
    DRIVE_TOTAL_GB+=("$total_gb")
  done < <(df -Pk 2>/dev/null | awk 'NR>1')

  # Also check for any custom path provided by the user
  if [ -n "${AGENT_007_EXTRA_DRIVE:-}" ] && [ -d "$AGENT_007_EXTRA_DRIVE" ]; then
    local ek ef et
    ek="$(df -Pk "$AGENT_007_EXTRA_DRIVE" | awk 'NR==2 {print $4}')"
    et="$(df -Pk "$AGENT_007_EXTRA_DRIVE" | awk 'NR==2 {print $2}')"
    ef=$((ek / 1024 / 1024))
    et=$((et / 1024 / 1024))
    DRIVE_PATHS+=("$AGENT_007_EXTRA_DRIVE")
    DRIVE_LABELS+=("$(basename "$AGENT_007_EXTRA_DRIVE")")
    DRIVE_FREE_GB+=("$ef")
    DRIVE_TOTAL_GB+=("$et")
  fi
}

print_drives() {
  local i
  printf '\n%b%-4s %-40s %10s %10s%b\n' "$BOLD" "#" "DRIVE / MOUNT POINT" "FREE" "TOTAL" "$NC"
  printf '%.0s─' {1..70}; printf '\n'
  for i in "${!DRIVE_PATHS[@]}"; do
    printf '  %-2s  %-40s %7s GB %7s GB\n' \
      "$((i + 1))" "${DRIVE_PATHS[$i]}" "${DRIVE_FREE_GB[$i]}" "${DRIVE_TOTAL_GB[$i]}"
  done
  printf '\n'
}

# ── Pick a drive for a category ──────────────────────────────────────
pick_drive() {
  local category="$1"
  local description="$2"
  local default_idx="${3:-1}"
  local subfolder="${4:-}"
  local choice path

  printf '%b▸ %s%b\n' "$BOLD" "$category" "$NC"
  printf '  %s\n' "$description"
  if [ -n "$subfolder" ]; then
    printf '  (subfolder: %s)\n' "$subfolder"
  fi

  while true; do
    read -r -p "  Choose drive number [${default_idx}]: " choice
    choice="${choice:-$default_idx}"
    if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#DRIVE_PATHS[@]} )); then
      path="${DRIVE_PATHS[$((choice - 1))]}"
      if [ -n "$subfolder" ]; then
        path="$path/$subfolder"
      fi
      printf '  → %s\n\n' "$path"
      echo "$path"
      return 0
    elif [ "$choice" = "c" ] || [ "$choice" = "C" ]; then
      read -r -p "  Enter custom path: " path
      if [ -n "$path" ]; then
        printf '  → %s\n\n' "$path"
        echo "$path"
        return 0
      fi
    fi
    warn "Invalid choice. Enter a number (1-${#DRIVE_PATHS[@]}) or 'c' for custom path."
  done
}

# ── Write the config ─────────────────────────────────────────────────
write_config() {
  local out="$1"
  cat > "$out" <<ENVFILE
# Agent-007 Multi-Drive Storage Configuration
# Generated by AGENT-007-CHOOSE-STORAGE.sh on $(date)
# Source this file to route Agent-007 data across your drives.
#
# To regenerate: bash AGENT-007-CHOOSE-STORAGE.sh
# To override a single category: export AGENT_007_DRIVE_xxx=/your/path before running scripts.

# ── Primary Agent-007 home (app files, tools, crew data) ─────────────
export AGENT_007_DRIVE_APP="$CHOSEN_APP"

# ── LLM model storage (Ollama models — typically the largest) ────
export AGENT_007_DRIVE_LLM_MODELS="$CHOSEN_LLM"

# ── GGUF model files (Hugging Face GGUF picks) ──────────────────
export AGENT_007_DRIVE_GGUF="$CHOSEN_GGUF"

# ── Image generation models (checkpoints, flux, loras, vae …) ───
export AGENT_007_DRIVE_IMAGE_MODELS="$CHOSEN_IMAGE_MODELS"

# ── Generated outputs (images, renders, exports) ────────────────
export AGENT_007_DRIVE_OUTPUTS="$CHOSEN_OUTPUTS"

# ── Downloads (general download targets) ────────────────────────
export AGENT_007_DRIVE_DOWNLOADS="$CHOSEN_DOWNLOADS"

# ── Cache (HF cache, pip, torch, xdg) ──────────────────────────
export AGENT_007_DRIVE_CACHE="$CHOSEN_CACHE"

# ── Logs ────────────────────────────────────────────────────────
export AGENT_007_DRIVE_LOGS="$CHOSEN_LOGS"

# ── Runtime (venvs, temp, pid files, Ollama runtime) ────────────
export AGENT_007_DRIVE_RUNTIME="$CHOSEN_RUNTIME"

# ── GOAT app data ──────────────────────────────────────────────
export AGENT_007_DRIVE_GOAT_DATA="$CHOSEN_GOAT"

# ── Backward compatibility aliases ──────────────────────────────
export FKD1_ROOT="\$AGENT_007_DRIVE_APP"
export AGENT_007_HOME="\$AGENT_007_DRIVE_APP"
export OLLAMA_MODELS="\$AGENT_007_DRIVE_LLM_MODELS"
export AGENT_007_MODEL_STORE="\$AGENT_007_DRIVE_LLM_MODELS"
export AGENT_007_GGUF_STORE="\$AGENT_007_DRIVE_GGUF"
export GOAT_DATA_ROOT="\$AGENT_007_DRIVE_GOAT_DATA"
export GOAT_DOWNLOAD_DIR="\$AGENT_007_DRIVE_DOWNLOADS"
ENVFILE
}

# ── Also update .agent-007-one-folder.env if it exists ───────────────────
update_one_folder_env() {
  local root="$CHOSEN_APP"
  local envfile="$root/.agent-007-one-folder.env"
  [ -d "$root" ] || mkdir -p "$root"

  cat > "$envfile" <<'HEADER'
# Agent-007 One-Folder Environment (multi-drive aware)
# Auto-generated by AGENT-007-CHOOSE-STORAGE.sh
HEADER

  cat >> "$envfile" <<ENVBODY
export AGENT_007_HOME="$CHOSEN_APP"
export FKD1_ROOT="$CHOSEN_APP"
export AGENT_007_BRIDGE_WORKSPACE="$CHOSEN_APP"
export AGENT_007_TOOL_WORKSPACE="$CHOSEN_APP"
export AGENT_007_ASSET_ROOT="$CHOSEN_APP"

export OLLAMA_MODELS="$CHOSEN_LLM"
export AGENT_007_MODEL_STORE="$CHOSEN_LLM"
export AGENT_007_GGUF_STORE="$CHOSEN_GGUF"

export GOAT_DATA_ROOT="$CHOSEN_GOAT"
export GOAT_DOWNLOAD_DIR="$CHOSEN_DOWNLOADS"

export AGENT_007_OUTPUT_DIR="$CHOSEN_OUTPUTS"
export AGENT_007_IMAGE_OUTPUT_DIR="$CHOSEN_OUTPUTS/images"
export AGENT_007_IMAGE_MODEL_ROOT="$CHOSEN_IMAGE_MODELS"

export AGENT_007_LOG_DIR="$CHOSEN_LOGS"
export AGENT_007_IMAGE_LOG_DIR="$CHOSEN_LOGS"

export AGENT_007_RUNTIME_DIR="$CHOSEN_RUNTIME"
export AGENT_007_RUNTIME_HOME="$CHOSEN_RUNTIME"
export OLLAMA_HOME="$CHOSEN_RUNTIME"
export OLLAMA_RUNNERS_DIR="$CHOSEN_RUNTIME/runners"
export OLLAMA_TMPDIR="$CHOSEN_RUNTIME/tmp"
export TMPDIR="$CHOSEN_CACHE/tmp"

export HF_HOME="$CHOSEN_CACHE/huggingface"
export TRANSFORMERS_CACHE="$CHOSEN_CACHE/huggingface/transformers"
export HUGGINGFACE_HUB_CACHE="$CHOSEN_CACHE/huggingface/hub"
export XDG_CACHE_HOME="$CHOSEN_CACHE/xdg"
export TORCH_HOME="$CHOSEN_CACHE/torch"
export PIP_CACHE_DIR="$CHOSEN_CACHE/pip"

export OLLAMA_HOST="\${OLLAMA_HOST:-127.0.0.1:11434}"
export OLLAMA_CONTEXT_LENGTH="\${OLLAMA_CONTEXT_LENGTH:-32768}"
export OLLAMA_NUM_PARALLEL="\${OLLAMA_NUM_PARALLEL:-1}"
export OLLAMA_MAX_LOADED_MODELS="\${OLLAMA_MAX_LOADED_MODELS:-1}"

export AGENT_007_IMAGE_RENDER_ENDPOINT="\${AGENT_007_IMAGE_RENDER_ENDPOINT:-http://127.0.0.1:3344/api/draw}"
export GOAT_IMAGE_RENDER_ENDPOINT="\${GOAT_IMAGE_RENDER_ENDPOINT:-\$AGENT_007_IMAGE_RENDER_ENDPOINT}"
export AGENT_007_DRAW_PORT="\${AGENT_007_DRAW_PORT:-3344}"
export AGENT_007_CHAT_PORT="\${AGENT_007_CHAT_PORT:-3333}"
export GOAT_WEB_PORT="\${GOAT_WEB_PORT:-8765}"
export GOAT_INTEL_PORT="\${GOAT_INTEL_PORT:-5500}"

export AGENT_007_ALLOW_ONLINE="\${AGENT_007_ALLOW_ONLINE:-0}"
export AGENT_007_OFFLINE="\${AGENT_007_OFFLINE:-1}"
export HF_HUB_OFFLINE="\$AGENT_007_OFFLINE"
export TRANSFORMERS_OFFLINE="\$AGENT_007_OFFLINE"
ENVBODY

  ok "Updated: $envfile"
}

# ── Also update agent-007-image-runtimes.env if applicable ───────────────
update_image_runtimes_env() {
  local root="$CHOSEN_APP"
  local envfile="$root/agent-007-image-runtimes.env"
  local runtime_root="$root/image-runtimes"

  cat > "$envfile" <<ENVBODY
export AGENT_007_HOME="$CHOSEN_APP"
export AGENT_007_IMAGE_RUNTIME_ROOT="$runtime_root"
export AGENT_007_IMAGE_MODEL_ROOT="$CHOSEN_IMAGE_MODELS"
export AGENT_007_IMAGE_OUTPUT_DIR="$CHOSEN_OUTPUTS/images"
export AGENT_007_IMAGE_LOG_DIR="$CHOSEN_LOGS"
export AGENT_007_IMAGE_PYTHON="\${AGENT_007_IMAGE_PYTHON:-\$(command -v python3 2>/dev/null || command -v python 2>/dev/null || echo python3)}"
export HF_HOME="$CHOSEN_CACHE/huggingface"
export TRANSFORMERS_CACHE="$CHOSEN_CACHE/huggingface/transformers"
export HUGGINGFACE_HUB_CACHE="$CHOSEN_CACHE/huggingface/hub"
export XDG_CACHE_HOME="$CHOSEN_CACHE/xdg"
export TORCH_HOME="$CHOSEN_CACHE/torch"
export PIP_CACHE_DIR="$CHOSEN_CACHE/pip"
export COMFYUI_DIR="$runtime_root/ComfyUI"
export A1111_DIR="$runtime_root/stable-diffusion-webui"
export FORGE_DIR="$runtime_root/stable-diffusion-webui-forge"
export INVOKEAI_DIR="$runtime_root/InvokeAI"
export DIFFUSERS_DIR="$runtime_root/diffusers"
export AGENT_007_COMFY_PORT="\${AGENT_007_COMFY_PORT:-8188}"
export AGENT_007_A1111_PORT="\${AGENT_007_A1111_PORT:-7860}"
export AGENT_007_FORGE_PORT="\${AGENT_007_FORGE_PORT:-7861}"
export AGENT_007_INVOKEAI_PORT="\${AGENT_007_INVOKEAI_PORT:-9090}"
ENVBODY

  ok "Updated: $envfile"
}

# ── Create required directories ──────────────────────────────────────
create_directories() {
  say "Creating storage directories..."
  local d
  for d in \
    "$CHOSEN_APP" \
    "$CHOSEN_LLM" \
    "$CHOSEN_GGUF" \
    "$CHOSEN_IMAGE_MODELS" \
    "$CHOSEN_IMAGE_MODELS/checkpoints" \
    "$CHOSEN_IMAGE_MODELS/flux" \
    "$CHOSEN_IMAGE_MODELS/loras" \
    "$CHOSEN_IMAGE_MODELS/vae" \
    "$CHOSEN_IMAGE_MODELS/vae_approx" \
    "$CHOSEN_IMAGE_MODELS/controlnet" \
    "$CHOSEN_IMAGE_MODELS/embeddings" \
    "$CHOSEN_IMAGE_MODELS/upscalers" \
    "$CHOSEN_IMAGE_MODELS/clip" \
    "$CHOSEN_IMAGE_MODELS/clip_vision" \
    "$CHOSEN_IMAGE_MODELS/unet" \
    "$CHOSEN_IMAGE_MODELS/text_encoders" \
    "$CHOSEN_IMAGE_MODELS/ipadapter" \
    "$CHOSEN_IMAGE_MODELS/diffusers" \
    "$CHOSEN_IMAGE_MODELS/invokeai" \
    "$CHOSEN_OUTPUTS" \
    "$CHOSEN_OUTPUTS/images" \
    "$CHOSEN_DOWNLOADS" \
    "$CHOSEN_CACHE" \
    "$CHOSEN_CACHE/huggingface" \
    "$CHOSEN_CACHE/pip" \
    "$CHOSEN_CACHE/torch" \
    "$CHOSEN_CACHE/xdg" \
    "$CHOSEN_CACHE/tmp" \
    "$CHOSEN_LOGS" \
    "$CHOSEN_RUNTIME" \
    "$CHOSEN_RUNTIME/pids" \
    "$CHOSEN_RUNTIME/runners" \
    "$CHOSEN_RUNTIME/tmp" \
    "$CHOSEN_GOAT"; do
    mkdir -p "$d" 2>/dev/null || warn "Could not create: $d"
  done
  ok "Storage directories created."
}

# ── Print summary ────────────────────────────────────────────────────
print_summary() {
  printf '\n%b════════════════════════════════════════════════════════════%b\n' "$BOLD" "$NC"
  printf '%b  OSCAR STORAGE CONFIGURATION SUMMARY%b\n' "$BOLD" "$NC"
  printf '%b════════════════════════════════════════════════════════════%b\n' "$BOLD" "$NC"
  printf '  App / Home:        %s\n' "$CHOSEN_APP"
  printf '  LLM Models:        %s\n' "$CHOSEN_LLM"
  printf '  GGUF Models:       %s\n' "$CHOSEN_GGUF"
  printf '  Image Models:      %s\n' "$CHOSEN_IMAGE_MODELS"
  printf '  Outputs:           %s\n' "$CHOSEN_OUTPUTS"
  printf '  Downloads:         %s\n' "$CHOSEN_DOWNLOADS"
  printf '  Cache:             %s\n' "$CHOSEN_CACHE"
  printf '  Logs:              %s\n' "$CHOSEN_LOGS"
  printf '  Runtime:           %s\n' "$CHOSEN_RUNTIME"
  printf '  GOAT Data:         %s\n' "$CHOSEN_GOAT"
  printf '%b════════════════════════════════════════════════════════════%b\n\n' "$BOLD" "$NC"
}

# ── Main ─────────────────────────────────────────────────────────────
main() {
  printf '\n%b╔══════════════════════════════════════════════════════════╗%b\n' "$BOLD" "$NC"
  printf '%b║        AGENT-007 MULTI-DRIVE STORAGE CONFIGURATOR           ║%b\n' "$BOLD" "$NC"
  printf '%b╚══════════════════════════════════════════════════════════╝%b\n' "$BOLD" "$NC"
  printf '\nThis tool lets you choose which drive or folder to use for\n'
  printf 'each type of Agent-007 data. Large files (LLM models, image models)\n'
  printf 'can go on big/fast drives; small files (logs, cache) can stay local.\n'

  detect_drives

  if [ ${#DRIVE_PATHS[@]} -eq 0 ]; then
    die "No suitable drives detected. Mount a drive or set AGENT_007_EXTRA_DRIVE=/path."
  fi

  if [ "${1:-}" = "--list" ]; then
    print_drives
    exit 0
  fi

  print_drives
  printf 'Enter a drive number for each category, or %bc%b for a custom path.\n\n' "$BOLD" "$NC"

  # Find a good default (prefer FKD1 if present)
  local default_idx=1
  local i
  for i in "${!DRIVE_LABELS[@]}"; do
    if [ "${DRIVE_LABELS[$i]}" = "FKD1" ]; then
      default_idx=$((i + 1))
      break
    fi
  done

  CHOSEN_APP="$(pick_drive \
    "Agent-007 App / Home" \
    "Main Agent-007 folder: tools, crew data, scripts, web app." \
    "$default_idx" \
    "AGENT-007-ONE-FOLDER")"

  CHOSEN_LLM="$(pick_drive \
    "LLM Models (Ollama)" \
    "Ollama model blobs. 29-model pack is ~400GB. Put on your biggest/fastest drive." \
    "$default_idx" \
    "models/ollama")"

  CHOSEN_GGUF="$(pick_drive \
    "GGUF Models" \
    "Hugging Face GGUF files. Can be tens of GB." \
    "$default_idx" \
    "models/gguf")"

  CHOSEN_IMAGE_MODELS="$(pick_drive \
    "Image Models" \
    "Checkpoints, FLUX, LoRA, VAE, ControlNet, embeddings, upscalers." \
    "$default_idx" \
    "models/image")"

  CHOSEN_OUTPUTS="$(pick_drive \
    "Outputs" \
    "Generated images, renders, exports." \
    "$default_idx" \
    "outputs")"

  CHOSEN_DOWNLOADS="$(pick_drive \
    "Downloads" \
    "General download targets." \
    "$default_idx" \
    "downloads")"

  CHOSEN_CACHE="$(pick_drive \
    "Cache" \
    "HF cache, pip, torch, xdg — can grow large with model downloads." \
    "$default_idx" \
    "cache")"

  CHOSEN_LOGS="$(pick_drive \
    "Logs" \
    "Agent-007/GOAT service logs." \
    "$default_idx" \
    "logs")"

  CHOSEN_RUNTIME="$(pick_drive \
    "Runtime" \
    "Venvs, Ollama runtime, temp files, PID files." \
    "$default_idx" \
    "runtime")"

  CHOSEN_GOAT="$(pick_drive \
    "GOAT App Data" \
    "GOAT Royalty App data files." \
    "$default_idx" \
    "data")"

  print_summary

  # Write configs
  local config_out="$CHOSEN_APP/.agent-007-storage-config.env"
  write_config "$config_out"
  ok "Storage config saved: $config_out"

  # Also write a copy next to this script
  if [ "$SCRIPT_DIR" != "$CHOSEN_APP" ]; then
    write_config "$SCRIPT_DIR/.agent-007-storage-config.env"
    ok "Storage config copy: $SCRIPT_DIR/.agent-007-storage-config.env"
  fi

  create_directories
  update_one_folder_env
  update_image_runtimes_env

  printf '\n%b DONE! %b Your Agent-007 scripts will now use the drives you chose.\n' "$GREEN" "$NC"
  printf 'Config file: %s\n' "$config_out"
  printf '\nTo reconfigure later, run:\n'
  printf '  bash %s/AGENT-007-CHOOSE-STORAGE.sh\n' "$SCRIPT_DIR"
  printf '\nTo test your setup:\n'
  printf '  bash %s/TEST-AGENT-007-ONE-FOLDER.sh\n' "$CHOSEN_APP"
  printf '\n'
}

main "$@"
