#!/usr/bin/env bash
# AGENT-007-SETUP-NAS.sh — Create the Agent-007 folder structure on a NAS.
# Run this AFTER the NAS is mounted (e.g. /Volumes/SPEEDYSCLOUD).
#
# Usage:
#   bash AGENT-007-SETUP-NAS.sh                     # auto-detect mounted NAS
#   bash AGENT-007-SETUP-NAS.sh /Volumes/SPEEDYSCLOUD  # explicit mount point
set -euo pipefail

GREEN='\033[0;32m'; CYAN='\033[0;36m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { printf '%b[INFO]%b %s\n' "$CYAN" "$NC" "$*"; }
ok()    { printf '%b[OK]%b   %s\n' "$GREEN" "$NC" "$*"; }
warn()  { printf '%b[WARN]%b %s\n' "$YELLOW" "$NC" "$*"; }
die()   { printf '%b[FAIL]%b %s\n' "$RED" "$NC" "$*"; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_COMMON="$SCRIPT_DIR/agent-007-storage-common.sh"
[ -f "$_COMMON" ] && . "$_COMMON"

# ── Detect or accept NAS mount point ──────────────────────────────
detect_nas() {
  local os mounts
  os="$(uname -s 2>/dev/null || echo unknown)"
  case "$os" in
    Darwin)  mounts=(/Volumes/*) ;;
    Linux)   mounts=(/mnt/* /media/*/* /run/media/*/* 2>/dev/null) ;;
    *)       mounts=() ;;
  esac
  for m in "${mounts[@]}"; do
    [ -d "$m" ] || continue
    # Skip local system volumes
    case "$m" in
      /Volumes/Macintosh*|/Volumes/Recovery|/Volumes/Preboot|/Volumes/VM|/Volumes/Data) continue ;;
    esac
    # Prefer volumes with "cloud" or "nas" in the name (case insensitive)
    if echo "$m" | grep -iq 'cloud\|nas\|mycloud\|speedy'; then
      printf '%s\n' "$m"
      return 0
    fi
  done
  # Fallback: any non-system volume
  for m in "${mounts[@]}"; do
    [ -d "$m" ] || continue
    case "$m" in
      /Volumes/Macintosh*|/Volumes/Recovery|/Volumes/Preboot|/Volumes/VM|/Volumes/Data) continue ;;
    esac
    printf '%s\n' "$m"
    return 0
  done
  return 1
}

NAS_ROOT="${1:-}"
if [ -z "$NAS_ROOT" ]; then
  NAS_ROOT="$(detect_nas 2>/dev/null || true)"
  if [ -z "$NAS_ROOT" ]; then
    die "No NAS mount detected. Mount your NAS first or pass the path:
  bash $0 /Volumes/SPEEDYSCLOUD"
  fi
fi

[ -d "$NAS_ROOT" ] || die "Path not found: $NAS_ROOT"

printf '\n'
printf '%b╔══════════════════════════════════════════════╗%b\n' "$GREEN" "$NC"
printf '%b║       AGENT-007  NAS FOLDER SETUP           ║%b\n' "$GREEN" "$NC"
printf '%b╚══════════════════════════════════════════════╝%b\n' "$GREEN" "$NC"
printf '\n'
info "NAS mount point: $NAS_ROOT"

# ── Check free space ──────────────────────────────────────────────
FREE_KB="$(df -Pk "$NAS_ROOT" 2>/dev/null | awk 'NR==2{print $4}')"
FREE_GB=$(( ${FREE_KB:-0} / 1048576 ))
info "Free space: ${FREE_GB} GB"
[ "$FREE_GB" -lt 5 ] && warn "Low free space on NAS (${FREE_GB} GB)."

# ── Create AGENT-007 directory structure ──────────────────────────
BASE="$NAS_ROOT/AGENT-007"

DIRS=(
  "$BASE"
  "$BASE/models/ollama"
  "$BASE/models/gguf"
  "$BASE/models/image/checkpoints"
  "$BASE/models/image/flux"
  "$BASE/models/image/loras"
  "$BASE/models/image/vae"
  "$BASE/models/image/controlnet"
  "$BASE/models/image/upscale"
  "$BASE/models/image/clip"
  "$BASE/models/image/embeddings"
  "$BASE/outputs/images"
  "$BASE/outputs/renders"
  "$BASE/outputs/exports"
  "$BASE/downloads"
  "$BASE/cache/huggingface/hub"
  "$BASE/cache/huggingface/transformers"
  "$BASE/cache/pip"
  "$BASE/cache/torch"
  "$BASE/logs"
  "$BASE/runtime/venvs"
  "$BASE/runtime/pids"
  "$BASE/runtime/tmp"
  "$BASE/goat-data"
  "$BASE/goat-data/royalties"
  "$BASE/goat-data/analytics"
  "$BASE/goat-data/backups"
  "$BASE/tools"
  "$BASE/Shared"
  "$BASE/web-app"
)

CREATED=0
for d in "${DIRS[@]}"; do
  if [ ! -d "$d" ]; then
    mkdir -p "$d"
    CREATED=$((CREATED + 1))
  fi
done

ok "Created $CREATED directories under $BASE"

# ── Write a .agent-007-nas-info file ──────────────────────────────
cat > "$BASE/.agent-007-nas-info" <<NASEOF
# AGENT-007 NAS Info
# Auto-generated by AGENT-007-SETUP-NAS.sh on $(date)
NAS_ROOT="$NAS_ROOT"
AGENT_007_NAS_BASE="$BASE"
NAS_FREE_GB=$FREE_GB
NASEOF

ok "Wrote $BASE/.agent-007-nas-info"

# ── Summary ───────────────────────────────────────────────────────
printf '\n%bAGENT-007 NAS Structure:%b\n' "$CYAN" "$NC"
printf '  %s/\n' "$BASE"
printf '  ├── models/ollama/          (LLM models)\n'
printf '  ├── models/gguf/            (GGUF models)\n'
printf '  ├── models/image/           (checkpoints, FLUX, LoRA, VAE...)\n'
printf '  ├── outputs/images/         (generated images)\n'
printf '  ├── downloads/              (general downloads)\n'
printf '  ├── cache/                  (HF, pip, torch cache)\n'
printf '  ├── logs/                   (service logs)\n'
printf '  ├── runtime/                (venvs, pids, temp)\n'
printf '  ├── goat-data/              (GOAT Royalty data & backups)\n'
printf '  ├── tools/                  (scripts & utilities)\n'
printf '  ├── Shared/                 (shared binaries)\n'
printf '  └── web-app/                (web interface)\n'

printf '\n%bNext steps:%b\n' "$YELLOW" "$NC"
printf '  1. Run AGENT-007-CHOOSE-STORAGE.sh and point categories to:\n'
printf '     %s/models/ollama, %s/outputs, etc.\n' "$BASE" "$BASE"
printf '  2. Or run the launcher directly:\n'
printf '     bash AGENT-007-LAUNCH.sh\n'
printf '\n'
